In [1]:
import sys
sys.path.insert(0, "/home/fcdl/Develop/ICL/")
from data.iCIFAR import ICIFAR
from torchvision.transforms import transforms
import torch
import matplotlib.pyplot as plt
import numpy as np

In [3]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(ICIFAR.MEAN, ICIFAR.STD)])

augmentation = transforms.RandomCrop((32,32), padding=4)

data = ICIFAR('/home/fcdl/dataset', num_cl_first=5, num_cl_after=5, 
              augmentation=None, transform=transform, batch_size=8, run_number=0, workers=8)
#data.order

Files already downloaded and verified
Files already downloaded and verified


In [11]:
data.train_dataset[0][0].show()


In [8]:
proto = data.get_images_of_class(19)


proto_y = torch.ones(len(proto))*19

from data.common import DatasetPrototypes

proto_set = DatasetPrototypes(proto, proto_y, transform)

#print(torch.eq(proto[0], proto_set[0][0]))
print(proto_set[0][0])

tensor([[[ 1.8426,  1.8426,  1.8426,  ...,  0.9630,  1.2122,  0.7724],
         [ 1.8426,  1.8280,  1.8280,  ...,  0.5965,  0.4646,  0.2447],
         [ 1.8426,  1.8280,  1.8426,  ...,  0.8751,  0.5379, -0.1218],
         ...,
         [ 0.2740,  0.1860,  0.1567,  ..., -1.4559, -0.9428, -0.7815],
         [-0.1072, -0.1365, -0.0485,  ..., -1.5732, -0.4737,  0.1714],
         [-0.6203, -0.6056, -0.4150,  ..., -1.3973, -0.3564,  0.1274]],

        [[ 2.0012,  2.0012,  2.0012,  ...,  1.2367,  1.5272,  1.0686],
         [ 2.0012,  1.9859,  1.9859,  ...,  0.7934,  0.6710,  0.4570],
         [ 2.0012,  1.9859,  2.0012,  ...,  1.1450,  0.8239,  0.1359],
         ...,
         [ 0.9310,  0.8851,  0.8392,  ..., -1.6376, -0.9496, -0.7202],
         [ 0.5029,  0.4723,  0.5487,  ..., -1.6528, -0.1851,  0.5640],
         [-0.0322, -0.0322,  0.1512,  ..., -1.3471,  0.1359,  0.7475]],

        [[ 2.0254,  2.0254,  2.0254,  ...,  1.1447,  1.3010,  0.7755],
         [ 2.0254,  2.0111,  2.0111,  ...,  0

In [16]:
dl = data.get_dataloader_of_class(19)

ll = []
for img, tar in dl:
    ll.append(img)

images = torch.cat(ll)

for i in range(500):
    if not torch.all(torch.eq(images[i], proto_set[i][0])):
        print("Not same order")

In [4]:
def get_index_of_classes(target, classes):
    l = []

    if isinstance(classes, int):  # if only one class is given, make it a list
        classes = [classes]

    for cl in classes:
        l.append(torch.nonzero(target == cl).squeeze())
    return torch.cat(l)

dataset_full = data.train_dataset
classes = data.order[data.offset(2-1): data.offset(2)]
indices = get_index_of_classes(data.train_target, classes)

dataset = torch.utils.data.Subset(dataset_full, indices)

ds = torch.utils.data.ConcatDataset([dataset, proto_set])

data_loader = torch.utils.data.DataLoader(ds, batch_size=8, shuffle=True, num_workers=4)

for inp, tar in data_loader:
    print(inp.shape)
    print(tar)

torch.Size([8, 3, 32, 32])
tensor([ 6, 75, 57, 75,  6, 23, 88,  6])
torch.Size([8, 3, 32, 32])
tensor([57, 75, 75, 19, 75, 75,  6, 57])
torch.Size([8, 3, 32, 32])
tensor([23, 23, 57, 23, 23, 23, 88, 88])
torch.Size([8, 3, 32, 32])
tensor([57, 75, 75, 88, 88,  6, 57, 19])
torch.Size([8, 3, 32, 32])
tensor([88, 23, 57, 19, 75, 75, 19,  6])
torch.Size([8, 3, 32, 32])
tensor([19, 75, 88, 19, 19, 23, 57, 23])
torch.Size([8, 3, 32, 32])
tensor([ 6, 57, 57, 75, 75, 75, 75, 23])
torch.Size([8, 3, 32, 32])
tensor([75,  6, 88, 88, 88, 19, 23, 23])
torch.Size([8, 3, 32, 32])
tensor([88, 19, 23, 23, 23, 19, 19, 23])
torch.Size([8, 3, 32, 32])
tensor([19, 23, 75,  6, 57, 19, 75, 19])
torch.Size([8, 3, 32, 32])
tensor([ 6, 75, 57, 57, 23, 57,  6, 23])
torch.Size([8, 3, 32, 32])
tensor([57, 57, 19,  6, 57, 57, 57,  6])
torch.Size([8, 3, 32, 32])
tensor([ 6, 88, 19,  6, 23, 88, 19, 57])
torch.Size([8, 3, 32, 32])
tensor([ 6, 19,  6,  6, 57, 88, 88, 75])
torch.Size([8, 3, 32, 32])
tensor([19, 57, 19, 1

torch.Size([8, 3, 32, 32])
tensor([75, 88, 23, 19, 19, 57,  6, 19])
torch.Size([8, 3, 32, 32])
tensor([88, 19, 88, 88, 88, 23, 23, 75])
torch.Size([8, 3, 32, 32])
tensor([23, 57, 88, 88, 57, 88, 75, 57])
torch.Size([8, 3, 32, 32])
tensor([57, 88,  6, 23, 57, 23,  6,  6])
torch.Size([8, 3, 32, 32])
tensor([75, 57, 23, 19, 57, 88, 19,  6])
torch.Size([8, 3, 32, 32])
tensor([23, 75,  6, 23, 75, 57, 19,  6])
torch.Size([8, 3, 32, 32])
tensor([19, 23, 23,  6, 75, 19, 19, 57])
torch.Size([8, 3, 32, 32])
tensor([75, 57, 75, 57, 23, 88, 75, 23])
torch.Size([8, 3, 32, 32])
tensor([75, 57, 19, 19, 75, 88,  6, 57])
torch.Size([8, 3, 32, 32])
tensor([ 6, 19, 57, 75, 23, 57, 75,  6])
torch.Size([8, 3, 32, 32])
tensor([19, 88, 57, 88, 57, 57, 23, 19])
torch.Size([8, 3, 32, 32])
tensor([ 6, 57, 19,  6, 19, 23, 88, 19])
torch.Size([8, 3, 32, 32])
tensor([88, 19, 88, 57, 57, 19,  6, 23])
torch.Size([8, 3, 32, 32])
tensor([75, 57, 88, 19, 57, 19, 23, 23])
torch.Size([8, 3, 32, 32])
tensor([75, 19,  6, 8

torch.Size([8, 3, 32, 32])
tensor([75, 75, 23, 88, 23, 23, 88, 23])
torch.Size([8, 3, 32, 32])
tensor([19, 57, 19, 19, 19,  6, 75, 23])
torch.Size([8, 3, 32, 32])
tensor([75, 75,  6, 57, 88, 19, 57, 57])
torch.Size([8, 3, 32, 32])
tensor([75, 88,  6, 57, 75, 57, 23, 19])
torch.Size([8, 3, 32, 32])
tensor([23, 57, 23,  6, 57, 88, 19, 88])
torch.Size([8, 3, 32, 32])
tensor([23, 57, 19,  6, 19, 23, 57, 23])
torch.Size([8, 3, 32, 32])
tensor([19, 88, 23, 57, 19, 19, 23, 88])
torch.Size([8, 3, 32, 32])
tensor([19, 88, 57, 57, 75, 23, 57, 57])
torch.Size([8, 3, 32, 32])
tensor([23, 57, 19,  6, 19, 57, 57, 88])
torch.Size([8, 3, 32, 32])
tensor([ 6, 19, 88, 75, 88, 88, 19, 19])
torch.Size([8, 3, 32, 32])
tensor([19, 23, 23, 19,  6,  6, 88, 19])
torch.Size([8, 3, 32, 32])
tensor([88,  6, 19, 23,  6,  6,  6, 23])
torch.Size([8, 3, 32, 32])
tensor([88, 23,  6, 23, 75, 57, 88, 19])
torch.Size([8, 3, 32, 32])
tensor([ 6, 57, 19,  6, 19, 57, 23, 75])
torch.Size([8, 3, 32, 32])
tensor([57, 23, 19, 1

In [39]:
data_loader = data.next_iteration()

for inp, tar in data_loader:
    print(inp.shape)
    #print(tar)


torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 32, 32])
torch.Size([64, 3, 3

In [32]:
iteration=1
dl = data.test_dataloader(iteration=iteration)

x = [19, 47, 74, 40, 67, 21, 27, 24, 87, 13,  6, 57, 23, 88, 75]
print(f"They should be: {sorted(x[:iteration*5])}")

for input, target in dl:
    print(target.unique().sort()[0])



They should be: [6, 13, 19, 21, 23, 24, 27, 40, 47, 57, 67, 74, 75, 87, 88]
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 47, 57, 65, 67, 74, 75, 87,
        88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 65, 74, 75, 87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 65, 67, 74, 75, 87,
        88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74, 75,
        87, 88])
tensor([ 6,  8, 13, 19, 20, 21, 23, 24, 27, 32, 35, 40, 47, 57, 65, 67, 74,

In [5]:
data.reset_iteration()

In [15]:
import torch

x = [1,2,3,1,3,4]
set(torch.tensor(x))

{tensor(1), tensor(1), tensor(2), tensor(3), tensor(3), tensor(4)}

{1, 2, 3, 4, 5, 6}